name: cocoon
homepage: https://github.com/flutter/cocoon
publish_to: none

environment:
  sdk: '>=2.8.0-dev.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  angular_forms: ^3.0.0
  args:
  js:
  http:
  meta:
  json_annotation:

dev_dependencies:
  test: ^1.15.5
  build_test:
  json_serializable:
  # Enables the `pub run build_runner` command
  build_runner: ^1.7.0
  # Includes the JavaScript compilers
  build_web_compilers:
