name: cocoon
version: 0.0.1
homepage: https://github.com/flutter/cocoon
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.17
  browser: ^0.10.0
  meta: ^0.12.1
dev_dependencies:
  test: ^0.12.14
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    entry_points: web/main.dart
- $dart2js:
    minify: true
    sourceMaps: true
