name: cocoon
homepage: https://github.com/flutter/cocoon
publish_to: none

environment:
  sdk: '>=2.8.0-dev.10.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0+1
  angular_forms: ^2.1.0
  js:
  http:
  meta:
  json_annotation:

dev_dependencies:
  test: ^1.13.0
  build_test:
  json_serializable:
  # Enables the `pub run build_runner` command
  build_runner: ^1.7.0
  # Includes the JavaScript compilers
  build_web_compilers: 2.10.0
